### ISSUE TITLE
Problem with escaped Strings on query rules

### ISSUE THREAD

**Issue by CyberLine** [voxpupuli/puppet-proxysql#90]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.8
- Ruby: 2.5.1p273
- Distribution: Debian
- Module version: 2.0.0

## How to reproduce (e.g Puppet code you use)
```
  - "mysql_query_rule-2":
      rule_id: 2
      active: 1
      apply: 1
      match_pattern: "^SELECT `account`\\.\\* FROM `account` WHERE \\(\\(\\(`account`.`account_id` = .*\\)\\)\\)"
      cache_ttl: 10000
      destination_hostgroup: 20
```

## What are you seeing
`Notice: /Stage[main]/Test::Services::Proxysql/Proxy_mysql_query_rule[mysql_query_rule-2]/match_pattern: match_pattern changed '^SELECT `account`\\.\\* FROM `account` WHERE \\(\\(\\(`account`.`account_id` = .*\\)\\)\\)' to '^SELECT `account`\.\* FROM `account` WHERE \(\(\(`account`.`account_id` = .*\)\)\)'`

## What behaviour did you expect instead
Nothing changed

## Any additional information you'd like to impart
After initial import of escaped query rules (yaml needs  double backslashes) on every puppet run i got this notice telling me that the rule is changed because it doesn't compare correct as the rule in the proxy is correct with single backslash.

**Comment by HeWhoWas** [comment]
My situation was a little bit different - however fundamentally the same. Given the following:

```
  - oddly_specific_rule_unknown_origin-3:
      rule_id: 13
      match_pattern: select\s+v.videoID\s+from\s+content.videos\s+v\s+inner\s+join\s+content.site_mapping\s+sm\s+on\s+sm.videoID\s+=\s+v.videoID\s+and\s+sm.siteID=(\d+)\s+where\s+v.state\s+=\s+''APPROVED''\s+and\s+v.reference\s+=\s+''(\d+)''\s+and\s+v.external_ref\s+=\s+''TV''\s+ORDER\s+BY\s+v.episode\s+ASC\s+LIMIT\s+1
      apply: 0
      active: 1
```

Would result in:
```
match_pattern changed 
'select\\s+v.videoID\\s+from\\s+content.videos\\s+v\\s+inner\\s+join\\s+content.site_mapping\\s+sm\\s+on\\s+sm.videoID\\s+=\\s+v.videoID\\s+and\\s+sm.siteID=(\\d+)\\s+where\\s+v.state\\s+=\\s+\'APPROVED\'\\s+and\\s+v.reference\\s+=\\s+\'(\\d+)\'\\s+and\\s+v.external_ref\\s+=\\s+\'TV\'\\s+ORDER\\s+BY\\s+v.episode\\s+ASC\\s+LIMIT\\s+1' to 
'select\s+v.videoID\s+from\s+content.videos\s+v\s+inner\s+join\s+content.site_mapping\s+sm\s+on\s+sm.videoID\s+=\s+v.videoID\s+and\s+sm.siteID=(\d+)\s+where\s+v.state\s+=\s+\'\'APPROVED\'\'\s+and\s+v.reference\s+=\s+\'\'(\d+)\'\'\s+and\s+v.external_ref\s+=\s+\'\'TV\'\'\s+ORDER\s+BY\s+v.episode\s+ASC\s+LIMIT\s+1
```
Effectively the changes are is:

1. In the original YAML config, single quotes are escaped by having two in a row: `''`:
```
''APPROVED'' in YAML becomes
\'\'APPROVED\'\'\ when escaped by Puppet/Hiera (?)
\'APPROVED\' when retrieved from the ProxySQL instance at runtime
```
2. The function that queries mysql returns the string with both single quotes and backslashes escaped with a backslash
Escaping `\` with a `\`
```
\s+ in YAML becomes
\\s+ when retrieved from the ProxySQL instance at runtime
